### ISSUE TITLE
Create docker image for Classic HydraNorth

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/DIDockerImages#1]
- [ ] a lightweight single container that can deploy the application easy and fast, to share with our colleagues, hydra community, and for quick demo/bug fix purpose
- [ ] a multiple containers application stack, remain as lightweight as possible, but have essential integrated components. It will be used as the development environment. Consult with other developers on preferences as needed.

**Comment by astrilet** [comment]
Single image containers have been created for HydraNorth running on sqlite3 or mysql;
images have been deposited in  docker hub under ualibraries/hydra_north_mysql and ualibraries/hydra_north_sqlite

**Comment by astrilet** [comment]
This issue was moved to ualbertalib/DIDocker_HydraNorth#1
